### ISSUE TITLE
Should we bundle HA provided dependencies?

### ISSUE THREAD

**Issue by nathan-gs** [nathan-gs/ha-map-card#53]
Currently we include leaflet and lit in our generated map-card.js, I wonder if it would be better to leave them out given HomeAssistant provides these anyway. 

WDYT @thybag?

**Comment by thybag** [comment]
It'd probably be nice if we could find a way to do it, as Leaflets quite a bit of the code weight. 
HA's code splitting tends to make it hard to request specific resources when their internal component isn't on the page so unsure if will be possible. So far as i could see there were very few custom map cards (Aside from your own) out there, otherwise would be tempted to have a peak at how they'd done it.
