### ISSUE TITLE
[FR] Add an overriding "icon" option

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#84]
Assume some entity has some icon (default or set by a user).
If `display: icon` - then this icon will be shown on a marker.
Is it possible to add a new option - `icon`?
If it is set - then this icon will be shown instead of a "native" one.

I thought: since we have a possibility to set an `image`, then it would be great to have an `icon` as well ))))

**Comment by MelleD** [comment]
It would be cool to have an option to simply put an icon instead of a picture/image, also when the sensor do not include it.

The behavior when the sensor does not have an icon is also interesting. That HA somehow finds a suitable icon in the dialog.

For example on the map I see the label: display is icon

![Bildschirmfoto 2024-09-10 um 00.13.44|244x160](upload://fcd7ZcmvBswIlS0eDzXuin8wOLp.png)

If I click on it. I have an icon, but into the attributes there is no icon attribute.
![Bildschirmfoto 2024-09-10 um 00.13.54|194x116](upload://69WH0qVGsE3XOY56nXDCOziHr2B.png)

Would be nice, just to use the same logic like the detail dialog and/or give an option on the entity section to override the icon

**Comment by nathan-gs** [comment]
@MelleD @ildar170975 this is fixed in [v1.9.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.9.0)

**Comment by ildar170975** [comment]
@nathan-gs
@thybag 
Thank you very very much, guys.
